apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"config.openshift.io/v1","kind":"OAuth","metadata":{"annotations":{"include.release.openshift.io/ibm-cloud-managed":"true","include.release.openshift.io/self-managed-high-availability":"true","include.release.openshift.io/single-node-developer":"true","release.openshift.io/create-only":"true"},"creationTimestamp":"2022-05-03T10:52:40Z","generation":3,"name":"cluster","ownerReferences":[{"apiVersion":"config.openshift.io/v1","kind":"ClusterVersion","name":"version","uid":"cb09eeb2-48b1-47cf-811b-1c99db049371"}],"resourceVersion":"102821","uid":"3275ed64-5a64-4153-a90e-5b33447107e8"},"spec":{"identityProviders":[{"htpasswd":{"fileData":{"name":"localusers"}},"mappingMethod":"claim","name":"myusers","type":"HTPasswd"}]}}
    release.openshift.io/create-only: "true"
  creationTimestamp: "2022-05-03T10:52:40Z"
  generation: 5
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: cb09eeb2-48b1-47cf-811b-1c99db049371
  resourceVersion: "202223"
  uid: 3275ed64-5a64-4153-a90e-5b33447107e8
spec: 
  identityProviders:
  - htpasswd:
      fileData:
        name: localusers
    mappingMethod: claim
    name: myusers
    type: HTPasswd
