apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-ts
  name: hello-ts
  namespace: schedule-pods-ts
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-ts
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-ts
    spec:
      containers:
      - image: quay.io/redhattraining/hello-world-nginx:v1.0
        imagePullPolicy: Always
        name: hello-world-nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        client: ACME
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
