apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2022-08-20T03:57:36Z"
  generation: 4
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 941351e0-6f04-421c-86b5-a5e9a6db8450
  resourceVersion: "90453"
  uid: 96df7869-ade0-4fc8-87a7-c1a6c59528bf
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: test-idp-secret
    mappingMethod: claim
    name: myusers
    type: HTPasswd
