apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  creationTimestamp: "2022-05-03T10:52:40Z"
  generation: 11
  name: cluster
  resourceVersion: "337780"
  uid: 3275ed64-5a64-4153-a90e-5b33447107e8
spec: 
  identityProviders:
  - htpasswd:
      fileData:
        name: auth-review
    mappingMethod: claim
    name: htpasswd
    type: HTPasswd
